FMS/Controllers/LandingController.cs
using System;
using FMS.Services.Classes;
using System.Web.Mvc;
using FMS.Core.Models;
using FMS.Core.Helper;
using System.Threading.Tasks;

using System.Linq;
using FMS.App_Start;


namespace FMS.Controllers
{
    public class LandingController : BaseController
    {
        // GET: Landing
        public async Task<ActionResult> Index(string key)
        
        {
            ViewBag.IsKeyValid = false;
            LandingViewModel landingViewModel = new LandingViewModel();
            if (!string.IsNullOrEmpty(key))
            {
                var client = UserManager.GetClientAdminByKey(key);
                ViewBag.ClientInformation = client;
                if (client != null)//no client n reference to key
                {
                    var clients = await UserManager.GetCountByUserId(client.Id);
                    landingViewModel.LstSlider = ClientBasicInfoManager.GetSlidersList(client.Id);
                    landingViewModel.LstPlan = PlanManager.GetPlansList(client.Id);
                    landingViewModel.Client = clients.Item1;
                    landingViewModel.Trainer = clients.Item2;
                    landingViewModel.Years = clients.Item3;
                    landingViewModel.Key = key;
                    ViewBag.key = client.Id;
                    ViewBag.IsKeyValid = true;
                }
                else
                {
                    ViewBag.Message = "Invalid key entered";
                }
            }
            else
            {
                ViewBag.Message = "Please enter vaild key";
            }
            return View(landingViewModel);
        }


        /// <summary>
        /// Contact us
        /// </summary>
        /// <returns></returns>

        public ActionResult ContactUs(string siteKey)

        
        {
            var client = UserManager.GetClientAdminByKey(siteKey);
            ViewBag.Key = client.Id;
            ViewBag.ClientInformation = client;
            ViewBag.IsKeyValid = true;
            return View();
        }

        /// <summary>
        /// Sent email 
        /// </summary>
        /// <param name="contactUsModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> SendEmail(ContactUsModel contactUsModel)
        {
            ModelState.Remove("OwnerId");
            if (ModelState.IsValid)
            {
                string successMessage = "Email Sent Successfully!";
                //send Email here         
                var paths = (AppDomain.CurrentDomain.BaseDirectory + @"Views\Shared\EmailTemplate\SetPassword.cshtml");
                var EmailBody = System.IO.File.ReadAllText(paths);

                var callbackUrl = Url.Action("ResetUserAccessPassword", "Account", new { userId = contactUsModel.Id, email = contactUsModel.Email }, protocol: Request.Url.Scheme);
                string body = EmailBody.Replace("#name#", contactUsModel.Name).Replace("#url#", callbackUrl);

                string subject = contactUsModel.Subject;
                EmailModel emailModel = new EmailModel
                {
                    FromEmail = "FMS",
                    From = "FMS",
                    ToEmail = contactUsModel.Email,
                    Subject = subject,
                    Body = body
                };
                await EmailSender.SendEmailAsync(contactUsModel.Email, subject, body);
                return Json(new
                {
                    success = true,
                    message = successMessage,
                    JsonRequestBehavior.AllowGet
                });
            }
            else
            {
                return Json(new
                {
                    success = false,
                    message = "Something Went Wrong!",
                    JsonRequestBehavior.AllowGet
                });
            }
        }
    }

}

FMS/Controllers/ProfileController.cs
using FMS.App_Start;
using FMS.Core.Models;
using FMS.Services.Classes;
using System;
using System.Web.Mvc;

namespace FMS.Controllers
{
    [AuthorizationFilter]
    public class ProfileController : BaseController
    {
        #region Profile
        public ActionResult Index()
        {
            var userId = SessionHelper.UserId;
            var userDetailModel = new UserDetailModel();
            if (!string.IsNullOrEmpty(userId))
            {
                userDetailModel = UserManager.GetUserDetail(Convert.ToInt32(userId));
            }
            userDetailModel = userDetailModel == null ? new UserDetailModel() : userDetailModel;
            userDetailModel.UserId = Convert.ToInt32(userId);
            return View(userDetailModel);
        }

        /// <summary>
        /// Update User Detail
        /// </summary>
        ///  <param name="userDetailModel"></param>
        /// <returns></returns> 
        [HttpPost]
        public JsonResult Add(UserDetailModel userDetailModel)
        {
            ModelState.Remove("Id");
            string successMessage = (userDetailModel.Id != 0) ? "Profile Updated Successfully!" : " Profile Added Successfully!";
            try
            {
                if (ModelState.IsValid)
                {
                    var result = UserManager.UpdateUserDetail(userDetailModel);
                    if (result)
                    {
                        return Json(new
                        {
                            success = true,
                            message = successMessage,
                            JsonRequestBehavior.AllowGet
                        });
                    }
                }
                return Json(new
                {
                    success = false,
                    message = "Something Went Wrong!",
                    JsonRequestBehavior.AllowGet
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    success = false,
                    message = "Something Went Wrong!",
                    JsonRequestBehavior.AllowGet
                });
            }
        }

        #endregion
    }
}

FMS/Views/Shared/_Header.cshtml
@{
    string profileImageUrl = FMS.App_Start.FMSConfigurationManager.PortalUrl + "/Content/imgs/profile-icon.png";
    var userId = FMS.App_Start.SessionHelper.UserId;

    if (!string.IsNullOrEmpty(userId))
    {
        var userDetail = FMS.Services.Classes.UserManager.GetUserDetail(Convert.ToInt32(userId));
        if (userDetail != null && !string.IsNullOrEmpty(userDetail.ProfilePic))
        {
            profileImageUrl = userDetail.ProfilePic;
        }
    }
    var subscriptionDetail = FMS.Services.Classes.SubscriptionManager.IsStoreFreeTrialAndSubscriptionExpire(Convert.ToInt32(userId));
    var userRole = FMS.Services.Classes.RoleManager.GetUserRoleByUserId(Convert.ToInt32(userId));


}

<!-- navbar -->

<!-- Navbar -->
<nav class="navbar navbar-expand-md navbar-light">
    <!-- Collapse button -->
    <button class="navbar-toggler ml-auto mt-2" type="button" data-toggle="collapse" data-target="#basicExampleNav1"
            aria-controls="basicExampleNav1" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse mt-2" id="basicExampleNav1">
        <div class="navbar-nav ml-auto"></div>

        <!-- notification -->
        @if (userRole != null)
        {
            if (userRole.RoleName == FMS.Core.Enums.UserRole.Trainee.ToString())
            {
                if (subscriptionDetail != null)
                {
                    if (subscriptionDetail.DefaultSubscriptionExpirationDays  < 5)
                    {
                        <ul class="nav navbar-nav navbar-right notification-badge float-right">
                            <li>
                                <span class="padding-5">Your trial will expire in <span class="badge badge-nav-danger">@subscriptionDetail.RemainingSubscriptionExpirationDays</span> days <a href="@Url.Action("/index")" class="badge badge-nav-danger padding-5">view pricing options</a> </span>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="nav navbar-nav navbar-right notification-badge float-right">
                            @if (subscriptionDetail.RemainingSubscriptionExpirationDays > 5 && subscriptionDetail.RemainingSubscriptionExpirationDays < 30 && !subscriptionDetail.IsActive)
                            {
                                <li>
                                    <span class="padding-5">Your trial will expire in <span class="badge badge-nav">@subscriptionDetail.RemainingSubscriptionExpirationDays</span> days <a href="@Url.Action("/index")" class="badge badge-nav padding-5">view pricing options</a> </span>
                                </li>
                            }
                            @*else if (subscriptionDetail.RemainingSubscriptionExpirationDays >= 0 && subscriptionDetail.RemainingSubscriptionExpirationDays <= 5 && !subscriptionDetail.IsActive)
                            {
                                <li>
                                    <span class="padding-5">Your trial will expire in <span class="badge badge-nav-danger">@subscriptionDetail.RemainingSubscriptionExpirationDays</span> days <a href="@Url.Action("subscription/index")" class="badge badge-nav-danger padding-5">view pricing options</a> </span>
                                </li>
                            }*@
                            else if (subscriptionDetail.RemainingSubscriptionExpirationDays < 0 && !subscriptionDetail.IsActive)
                            {
                                <li>
                                    <span class="padding-5">Your subscription has expired by <span class="badge badge-nav-danger">@subscriptionDetail.RemainingSubscriptionExpirationDays</span> days <a href="@Url.Action("/index")" class="badge badge-nav-danger padding-5">view pricing options</a> </span>
                                </li>
                            }
                            @*else if (!subscriptionDetail.IsActive)
                            {
                                <li>
                                    <span class="padding-5"><a href="@Url.Action("subscription/index")" class="badge badge-nav padding-5">view pricing options</a> </span>
                                </li>
                            }*@

                        </ul>
                    }

                }
            }
        }
        else
        {
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="#!" class="nav-link navbar-link-2 waves-effect">
                        <i class="far fa-bell fa-2x"></i>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect p-0" id="navbarDropdownMenuLink3" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="true">
                        <img id="UserProfileImage" src="@profileImageUrl" class="img-circle profile-img" alt="Cinque Terre">
                        @Session["Username"]
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="@Url.Action("Index", "Profile")">Profile Setting</a>
                        <a class="dropdown-item" href="#!">Another action</a>
                        <a class="dropdown-item" href="#!">Something else here</a>

                    </div>
                </li>

            </ul>
        }
        <!-- /notification -->
        <!-- Right -->


    </div>
    <!-- Links -->

</nav>
<!-- Navbar -->

FMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> FMS - @ViewBag.Title</title>
    <link href="~/Content/imgs/FMSdxp_icon_teal.png" rel="shortcut icon" type="image/x-icon" />
    @{
        var portalUrl = FMS.App_Start.FMSConfigurationManager.PortalUrl;
        string actionName = HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("action");
        string controllerName = HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("controller");
        string path = controllerName + "/" + actionName;
    }


    <script>

        var baseUrl = '@portalUrl';
        var current_path = '@path';
        var current_role = '@FMS.App_Start.SessionHelper.UserRoles';
    </script>

    @Styles.Render("~/Content/css/fmsUI")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="page-wrapper chiller-theme toggled">

        @Html.Partial("_SideNav", FMS.Services.Classes.FunctionManager.GetAll(FMS.App_Start.SessionHelper.UserRoles))
        @Html.Partial("_Header")
        <!-- sidebar-wrapper  -->
        <main class="page-content">
            <div class="container-fluid">
                @RenderBody()
                <footer class="text-center">
                </footer>
            </div>
        </main>
        <!-- page-content" -->
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/siteJs")
    @RenderSection("scripts", required: false)

    <div id="loader" class="modal loading" style="display: none">
        <div class="loaderImg">
            <img src="~/Content/images/blue-loader.gif" />
        </div>
    </div>
    <div id="common-modal-pop-up" class="modal" role="dialog">
    </div>
</body>
</html>

FMS/Views/Shared/_LayoutLanding.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>FMS - @ViewBag.Title </title>
    <link href="~/Content/imgs/FMSdxp_icon_teal.png" rel="shortcut icon" type="image/x-icon" />
    <link rel="preconnect" href="https://fonts.gstatic.com/">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&amp;family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&amp;display=swap" rel="stylesheet">
    @{
        var portalUrl = FMS.App_Start.FMSConfigurationManager.PortalUrl;
        var basicInfo = new FMS.Core.Models.ClientBasicInfoViewModel();

        if (ViewBag.key != null)
        {
            basicInfo = FMS.Services.Classes.ClientBasicInfoManager.GetBasicInfosList(ViewBag.key);
        }

        var key = ViewBag.key;
    }
    @Styles.Render("~/bundles/landingPageStyle")
    <script>
          var baseUrl = '@portalUrl';
    </script>
</head>
<body>
    @if (ViewBag.IsKeyValid )
    {
        <div class="top-wrap">
            <div class="container-xl">
                <div class="row justify-/Content-end">
                    <div class="col-md topper d-flex align-items-xl-center">
                        <div class="text">
                            <a href="#">
                                <span class="icon fa fa-phone"></span>
                                @if (ViewBag.ClientInformation.Phone != null)
                                {
                                    <span class="text">@ViewBag.ClientInformation.Phone</span>
                                }
                            </a>
                        </div>
                    </div>
                    <div class="col-md topper d-flex align-items-xl-center justify-/Content-end">
                        <ul class="ftco-social">
                            @if (basicInfo != null && basicInfo.TwitterUrl != null)
                            {
                                <li><a href="@basicInfo.TwitterUrl" class="d-flex align-items-center justify-/Content-center"><span class="fab fa-twitter"></span></a></li>
                            }
                            @if (basicInfo != null && basicInfo.FacebookUrl != null)
                            {
                                <li><a href="@basicInfo.FacebookUrl" class="d-flex align-items-center justify-/Content-center"><span class="fab fa-facebook"></span></a></li>
                            }
                            @if (basicInfo != null && basicInfo.InstagramUrl != null)
                            {
                                <li><a href="@basicInfo.InstagramUrl" class="d-flex align-items-center justify-/Content-center"><span class="fab fa-instagram"></span></a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <nav class="navbar navbar-expand-lg  ftco-navbar-light">
            <div class="container-xl">
                <a class="navbar-brand d-flex align-items-center" href="@Url.Action("Index", "Home")">
                    <div class="icon d-flex align-items-center justify-/Content-center"><span class="fas fa-dumbbell"></span></div>
                    @if (basicInfo != null && !string.IsNullOrEmpty(basicInfo.Heading))
                    {
                        <span class="">@basicInfo.Heading <small> @basicInfo.SubHeading</small></span>
                    }
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupported" aria-controls="navbarSupported" aria-expanded="true" aria-label="Toggle navigation">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse border-top-custom" id="navbarSupported">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0 me-lg-5">
                        <li class="nav-item"><a class="nav-link active" href="@Url.Action("Index", "Home")">Home</a></li>
                        <li class="nav-item"><a class="nav-link active" href="@Url.Action("ContactUs", "Landing" , new {SiteKey = ViewBag.ClientInformation.SiteKey})">Contact</a></li>
                    </ul>
                    <a class="btn-custom" href=@Url.Action("Register", "Account" ,new { clientId = key })>Become A Member</a>
                </div>
            </div>
        </nav>
    }

    @RenderBody()

    @if (ViewBag.IsKeyValid)
    {
        <footer class="ftco-footer">
            <div class="container-xl">
                <div class="row mb-5 pb-5 justify-content-between">
                    <div class="col-md-6 col-lg">
                        <div class="ftco-footer-widget mb-4">
                            <h2 class="ftco-heading-2 logo d-flex">
                                <a class="navbar-brand d-flex align-items-center" href="@Url.Action("Index", "Home")">
                                    <div class="icon d-flex align-items-center justify-content-center"><span class="fas fa-dumbbell"></span></div>
                                    @if (basicInfo != null)
                                    {
                                        <span class="">@basicInfo.Heading<small> @basicInfo.SubHeading</small></span>
                                    }
                                </a>
                            </h2>
                          
                            <ul class="ftco-footer-social list-unstyled mt-2">
                                @if (basicInfo != null && basicInfo.TwitterUrl != null)
                                {
                                    <li><a href="@basicInfo.TwitterUrl"><span class="fab fa-twitter"></span></a></li>
                                }
                                @if (basicInfo != null && basicInfo.FacebookUrl != null)
                                {
                                    <li><a href="@basicInfo.FacebookUrl"><span class="fab fa-facebook"></span></a></li>
                                }
                                @if (basicInfo != null && basicInfo.InstagramUrl != null)
                                {
                                    <li><a href="@basicInfo.InstagramUrl"><span class="fab fa-instagram"></span></a></li>
                                }
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-2">
                    </div>
                    <div class="col-md-6 col-lg-2">
                        <div class="ftco-footer-widget mb-4">
                            <h2 class="ftco-heading-2">Our Contacts</h2>
                            <div class="block-23 mb-3">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <span class="icon fa fa-home"></span>
                                            @if (ViewBag.ClientInformation.Address != null)
                                            {
                                                <span class="text">@ViewBag.ClientInformation.Address</span>
                                            }
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <span class="icon fa fa-phone"></span>
                                            @if (ViewBag.ClientInformation.Phone != null)
                                            {
                                                <span class="text">@ViewBag.ClientInformation.Phone</span>
                                            }
                                        </a>
                                    </li>
                                    <li><a href="#"><span class="icon fa fa-paper-plane"></span><span class="text"><span class="__cf_email__" data-cfemail="e48d8a828ba49d8b9196808b89858d8aca878b89">@ViewBag.ClientInformation.Email</span></span></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-4">
                        <div class="ftco-footer-widget mb-4">
                            <div class="row g-sm-2">
                                <div class="col-sm-3 col-md-3 col-lg-3">
                                    <a href="#" class="img gallery" style="background-image: url(/Content/images/landing/xperson_1.jpg)"></a>
                                </div>
                                <div class="col-sm-3 col-md-3 col-lg-3">
                                    <a href="#" class="img gallery" style="background-image: url(/Content/images/landing/xgallery-2.jpg)"></a>
                                </div>
                                <div class="col-sm-3 col-md-3 col-lg-3">
                                    <a href="#" class="img gallery" style="background-image: url(/Content/images/landing/xgallery-3.jpg)"></a>
                                </div>
                                <div class="col-sm-3 col-md-3 col-lg-3">
                                    <a href="#" class="img gallery" style="background-image: url(/Content/images/landing/xgallery-4.jpg)"></a>
                                </div>
                                <div class="col-sm-3 col-md-3 col-lg-3">
                                    <a href="#" class="img gallery" style="background-image: url(/Content/images/landing/xgallery-5.jpg)"></a>
                                </div>
                                <div class="col-sm-3 col-md-3 col-lg-3">
                                    <a href="#" class="img gallery" style="background-image: url(/Content/images/landing/xgallery-6.jpg)"></a>
                                </div>
                                <div class="col-sm-3 col-md-3 col-lg-3">
                                    <a href="#" class="img gallery" style="background-image: url(/Content/images/landing/xgallery-7.jpg)"></a>
                                </div>
                                <div class="col-sm-3 col-md-3 col-lg-3">
                                    <a href="#" class="img gallery" style="background-image: url(/Content/images/landing/xgallery-8.jpg)"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid px-0 py-5 bg-darken">
                <div class="container-xl">
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <p class="mb-0" style="color: rgba(255,255,255,.5); font-size: 13px;">
                                Copyright &copy;
                                <script data-cfasync="false" src="../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                                <script>document.write(new Date().getFullYear());</script> All rights reserved  <i class="fa fa-heart color-danger" aria-hidden="true"></i>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    }

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/landingPageScriptFile")
    @Scripts.Render("~/bundles/landingPageScript")
    @RenderSection("scripts", required: false)
</body>
</html>

FMS/Views/Shared/_Layout_Auth.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FMS - @ViewBag.Title </title>
    <link href="~/Content/imgs/FMSdxp_icon_teal.png" rel="shortcut icon" type="image/x-icon" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/modernizr")
    <!-- Custom styles for this template -->
    @Styles.Render("~/Content/css/fmsUI")
</head>
<body>
    <div class="d-flex align-itFMS-center bd-highlight vh-100">
        <div class="box w-100 d-flex justify-content-center">
            @RenderBody()
        </div>
    </div>

</body>
</html>

FMS/Views/Shared/_SideNav.cshtml
@model List<FMS.Core.Models.FunctionModel>
<a id="show-sidebar" class="btn btn-sm btn-primary mt-2" href="#" style="z-index: 100;">
    <i class="fas fa-bars"></i>
</a>
<nav id="sidebar" class="sidebar-wrapper sidebar-nav ">
    <div class="sidebar-content">
        <div class="sidebar-brand mt-2">
            <a href="@Url.Action("Index", "Landing")" class="h5 text-primary m-0">
                <h5 class="modal-title marketing-header">FMS</h5>
                @*<img src="~/Content/imgs/FMSdxp_header_teal.png" />*@
            </a>
            <div id="close-sidebar">
                <i class="fas fa-arrow-left"></i>
            </div>
        </div>
        <!-- sidebar-search  -->
        <div class="sidebar-menu">
            <ul>
                @{
                    string livePath = "";
                    //if (!Request.IsLocal)
                    //{
                    //    //livePath = "/portal/FMS";
                    //}
                    string actionName = HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("action");
                    string controllerName = HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("controller");
                    string path = controllerName + "/" + actionName;

                }
                @foreach (var function in Model)
                {
                    string className = "";
                    if (function.Url.ToLower().Contains(path.ToLower()))
                    {
                        className = "active";
                    }

                    <li class=" @className">
                        <a href="@(livePath+function.Url)">
                            <i class="@function.Icon @className"></i>
                            <span>@function.Title</span>
                        </a>
                    </li>

                }

            </ul>
        </div>
        <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->
    <div class="sidebar-footer p-2">
        <div class="d-flex justify-content-start ml-4">
            @*<a href="#" class="h6 m-0">
                    <i class="fas fa-sign-out-alt"></i>
                    Logout
                </a>*@

            <a href="@Url.Action("Logout", "Account")" class="h6 m-0">  <i class="fas fa-sign-out-alt"></i> Logout</a>
        </div>
    </div>
</nav>