FMS/Controllers/PlanController.cs
using FMS.App_Start;
using FMS.Core.Helper;
using FMS.Core.Models;
using FMS.Services.Classes;
using Serilog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace FMS.Controllers
{
    public class PlanController : BaseController
    {
        #region Method

        #region Plan

        /// <summary>
        /// view for showing plan
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// view for plan screen
        /// </summary>
        /// <param name="planModel"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public async Task<ActionResult> AddPlan(PlanModel planModel)
        {
            ModelState.Clear();
            planModel = planModel == null ? new PlanModel() : planModel;
            bool isReadMode = planModel.IsReadMode;
            if (planModel.Id > 0)
            {
                planModel = await PlanManager.GetPlanById(planModel.Id);
                planModel = planModel == null ? new PlanModel() : planModel;
                //planModel.LstFeature = await PlanManager.GetPlanFeatures(planModel.Id);
            }
            planModel.IsReadMode = isReadMode;
            string currentUserId = !string.IsNullOrEmpty(SessionHelper.UserId) ? SessionHelper.UserId : "";
            planModel.CreatedBy = string.IsNullOrEmpty(planModel.CreatedBy) ? currentUserId : planModel.CreatedBy;
            planModel.ModifiedBy = string.IsNullOrEmpty(planModel.ModifiedBy) ? currentUserId : planModel.ModifiedBy;

            return View("~/Views/Plan/AddPlan.cshtml", planModel);
        }

        /// <summary>
        /// plan feature view
        /// </summary>
        /// <param name="planId"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult PlanFeature(int planId, bool isReadMode = false)
        {
            PlanFeatureModel planFeatureModel = new PlanFeatureModel();
            planFeatureModel.Id = planId;
            planFeatureModel.IsReadMode = isReadMode;
            planFeatureModel.CreatedBy = !string.IsNullOrEmpty(SessionHelper.UserId) ? SessionHelper.UserId : "";

            //Call an asynchronous method
            return PartialView("~/Views/Plan/_PlanFeature.cshtml", planFeatureModel);
        }

        /// <summary>
        /// add/update plan
        /// </summary>
        /// <param name="planModel"></param>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> UpdatePlan(PlanModel planModel)
        {
            if (planModel.Id == 0)
            {
                ModelState.Remove("Feature");
            }
            bool responseStatus = false;
            string responseMessage = "Something Went Wrong!";
            if (ModelState.IsValid)
            {
                if (!PlanManager.IsPlanDuplicate(planModel))
                {
                    //assign ownerId
                    planModel.OwnerId = DataManager.ToNullableInt(SessionHelper.UserId);
                    planModel.SitePortalOwnerId = SessionHelper.SitePortalOwnerId;
                    var response = await PlanManager.UpdatePlan(planModel);
                    responseStatus = response.Item1;
                    responseMessage = response.Item2;
                    if (planModel.LstFeature != null && planModel.LstFeature.Count > 0)
                    {
                        //PlanFeatureModel planFeatureModel = new PlanFeatureModel()
                        //{
                        //    PlanId = planModel.Id,
                        //    CreatedBy = planModel.CreatedBy,
                        //    LstFeature = planModel.LstFeature
                        //};
                        //await PlanManager.UpdatePlanFeatureMapping(planFeatureModel);
                    }
                }
                else
                {
                    responseStatus = false;
                    responseMessage = "Plan Already Exist!";
                }
            }
            return Json(new
            {
                success = responseStatus,
                message = responseMessage,
                JsonRequestBehavior.AllowGet
            });
        }

        /// <summary>
        /// Check If plan name is exist  
        /// </summary>
        /// <param name="planModel"></param>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpPost]
        public JsonResult IsPlanDuplicate(PlanModel planModel)
        {
            return Json(!PlanManager.IsPlanDuplicate(planModel));
        }

        /// <summary>
        /// get all plan data table list
        /// </summary>
        /// <param name="parms"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public async Task<ActionResult> GetPlanList(jQueryDataTableParamModel parms)
        {
            var response = await PlanManager.GetPlansDataTable(parms);
            return Json(new
            {
                aaData = response.Item1,
                iTotalRecords = response.Item3,
                iTotalDisplayRecords = response.Item3
            }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Delete Plan 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public bool DeletePlan(long id)
        {
            try
            {
                var result = PlanManager.DeletePlan(id);
                if (result)
                {
                    PlanManager.DeleteAllPlanFeatureByPlanId(id);

                }
                return (result) ? true : false;
            }
            catch (Exception ex)
            {
                Log.Error(ex, "PlanController Delete");
                return false;
            }
        }

        /// <summary>
        /// Change Plan Status
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public bool ChangePlanStatus(long id)
        {
            try
            {
                return (PlanManager.UpdatePlanStatus(id)) ? true : false;
            }
            catch (Exception ex)
            {
                Log.Error(ex, "PlanController=>ChangePlanStatus ");
                return false;
            }
        }

        #region modal popup methods

        /// <summary>
        /// open plan modal popup
        /// </summary>
        /// <param name="id"></param>
        /// <param name="isReadMode"></param>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> OpenPlanModal(int id, bool isReadMode = false)
        {

            if (!Request.IsAjaxRequest())
                return null;
            PlanModel planModel = new PlanModel();
            if (id == 0)
            {
                planModel.planFeature = "d-none";
            }
            if (id > 0)
            {
                planModel = await PlanManager.GetPlanById(id);
                planModel = planModel == null ? new PlanModel() : planModel;

            }
            planModel.IsReadMode = isReadMode;

            string currentUserId = !string.IsNullOrEmpty(SessionHelper.UserId) ? SessionHelper.UserId : "";
            planModel.CreatedBy = string.IsNullOrEmpty(planModel.CreatedBy) ? currentUserId : planModel.CreatedBy;
            planModel.ModifiedBy = string.IsNullOrEmpty(planModel.ModifiedBy) ? currentUserId : planModel.ModifiedBy;

            return PartialView("~/Views/Plan/_AddEditPlanFeature.cshtml", planModel);
        }

        /// <summary>
        /// save the info of plan modal popup
        /// </summary>
        /// <param name="planModel"></param>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> UpdatePlanModal(PlanModel planModel)
        {

            bool responseStatus = false;
            string responseMessage = "Something Went Wrong!";
            if (ModelState.IsValid)
            {
                if (!PlanManager.IsPlanDuplicate(planModel))
                {       
                    //assign ownerId
                    planModel.OwnerId = DataManager.ToNullableInt(SessionHelper.UserId);
                    planModel.SitePortalOwnerId = SessionHelper.SitePortalOwnerId;
                    var response = await PlanManager.UpdatePlan(planModel);
                    responseStatus = response.Item1;
                    responseMessage = response.Item2;
                    if (responseStatus && planModel.Feature != null)
                    {
                        PlanFeatureModel planFeature = new PlanFeatureModel()
                        {
                            PlanId = planModel.Id,
                            Feature = planModel.Feature,
                            OwnerId = planModel.OwnerId,

                        SitePortalOwnerId =planModel.SitePortalOwnerId,
                        
                    };

                       
                        

                        PlanManager.UpdatePlanFeature(planFeature);
                    }

                }
                else
                {
                    responseStatus = false;
                    responseMessage = "Plan Already Exist!";
                }
            }
            return Json(new
            {
                success = responseStatus,
                message = responseMessage,
                JsonRequestBehavior.AllowGet
            });
        }

        #endregion

        #endregion 

        #region View features associated with plan

        /// <summary>
        ///view for selected plan feature
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult ViewPlanFeature()
        {
            return View();

FMS/Views/Plan/AddPlan.cshtml
@model FMS.Core.Models.PlanModel
@{
    string title = (Model != null && Model.Id == 0) ? "Add New Pricing Plan" : (Model != null && Model.IsReadMode) ? "View " + Model.Name : "Edit Pricing Plan";
    Layout = "~/Views/Shared/_LayoutSAAS.cshtml";
    var PortalUrl = FMS.App_Start.FMSConfigurationManager.PortalUrl;
    string buttonText = (Model != null && Model.IsReadMode) ? "View Features" : "Add Features";
}

<div id="content">
    <div class="panel panel-default">
        <div class=" panel-heading">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <h3 class="box-title">@title</h3>
                </div>
            </div>
        </div>

        <!-- /.box-header -->
        <div class="panel-body">
            <div id="PlanModule" class="pricingWizard">
                <form role="form" method="post"
                      id="frmAddNewPlan"
                      data-clear-form="false"
                      data-post-type='ajax'
                      action="/plan/updatePlan"
                      data-success-method="PlanViewModel.updatePlanSuccess">
                    @Html.HiddenFor(x => x.Id)
                    @Html.HiddenFor(x => x.IsReadMode)
                    @Html.HiddenFor(x => x.CreatedBy)
                    @Html.HiddenFor(x => x.ModifiedBy)
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                <div class="form-group">
                                    <label for="Name">Plan Name</label>
                                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control", @id = "PlanName" })
                                    @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <label for="Price">Price</label>
                                    <div class="input-icon">
                                        @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Price, "", new { @class = "text-danger" })
                                        <i>$</i>
                                    </div>
                                </div>

                               
                                <div class="form-group">
                                    <label for="Description">Plan Description</label>
                                    @Html.TextAreaFor(x => x.Description, new { @class = "form-control", @rows = "5" })
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                <div class="form-group">
                                    <br />
                                    <button type="button" class="btn btn-success notDisabled" onclick="PlanViewModel.showView(this)" data-viewName="planFeature" data-divId="PlanFeatureModule">
                                        @if (Model.IsReadMode)
                                        {
                                            <i class="fa fa-eye mr-1"></i>
                                        }
                                        else
                                        {
                                            <i class="fa fa-plus mr-1"></i>
                                        }
                                        @buttonText
                                    </button>
                                </div>
                                <div class="form-group ">
                                    <div class="card featureCard">
                                        @if (Model.LstFeature != null && Model.LstFeature.Count > 0)
                                        {
                                            <div class="card-body boxShadow padding-20">
                                                @for (var i = 0; i < Model.LstFeature.Count; i++)
                                                {
                                                    <div class="form-check">
                                                        @Html.HiddenFor(x => x.LstFeature[i].Id)
                                                        @Html.HiddenFor(x => x.LstFeature[i].Name)
                                                        <input class="form-check-input" type="checkbox"
                                                               name="@Html.NameFor(m => Model.LstFeature[i].IsChecked)"
                                                               id="@Html.IdFor(m =>Model.LstFeature[i].IsChecked)"
                                                               value="@(Model.LstFeature[i].IsChecked?"true":"false")"
                                                               onchange="onChangeCheckBoxSelection(this)"
                                                               @(Model.LstFeature[i].IsChecked ? "checked" : "")>
                                                        <label class="form-check-label" for="feature">
                                                            @Model.LstFeature[i].Name
                                                        </label>
                                                    </div>
                                                }
                                            </div>
                                        }
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox"
                                               name="@Html.NameFor(m => Model.IsDisplayOnPublicPage)"
                                               id="@Html.IdFor(m =>Model.IsDisplayOnPublicPage)"
                                               value="@(Model.IsDisplayOnPublicPage?"true":"false")"
                                               onchange="onChangeCheckBoxSelection(this)"
                                               @(Model.IsDisplayOnPublicPage ? "checked" : "")>
                                        <label class="form-check-label" for="feature">
                                            Display on Public Page
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="text-right margin-10">
                        <button type="submit" id="btn-frmAddNewPlan-submit" class="d-none"></button>
                        <a href="@PortalUrl/plan/index" class="btn btn-cancel notDisabled">Cancel</a>
                        <button type="button" id="btnSavePlan" class=" ladda-button btn btn-info" data-style="expand-right" onclick="PlanViewModel.updatePlan(this)" data-formId="frmAddNewPlan">Submit</button>
                    </div>
                </form>
            </div>

            <div id="PlanFeatureModule" class="d-none pricingWizard">
                @{Html.RenderAction("PlanFeature", "Plan", new { planId = Model.Id, isReadMode = Model.IsReadMode });}
            </div>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
</div>

<!-- #region scripts -->
@section Scripts
    {
    <script src="~/Scripts/Plan/PlanViewModel.js"></script>
    <script>
        $(document).ready(function () {
              var isReadMode =@Html.Raw(Json.Encode(Model.IsReadMode));
            if (isReadMode) {
                disabledFormInputs("frmAddNewPlan");
                disabledFormInputs("frmAddNewPlanFeature");
            }
            PlanViewModel.activeWizardName = "plan";
        });

    </script>
}
<!-- #endregion -->

FMS/Views/Plan/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="widget-group row">
    <div class="col-12">
        <div class="card">
            <!-- card-header -->
            <div class="card-header">
                <div class="row">
                    <div class="col">
                        <span class="h5 border-right-1 pr-2 marketing-header"><i class="icon-truck-fast"></i>Pricing Plans</span>
                    </div>
                    <div class="col col text-right">
                        <button class="btn btn-primary" id="btnAddPlan" onclick="PlanViewModel.openPlanModel(0)">
                           Pricing Plan <i class="fa fa-plus mr-1"></i>
                        </button>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <!-- card-body -->
            <div class="card-body">
                <table id="tblPlan" class="table table-bordered table-hover dt-responsive nowrap" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th data-class="expand">
                                <div class="table-header">
                                    <span class="column-title">Name</span>
                                </div>
                            </th>
                            <th data-hide="phone">
                                <div class="table-header">
                                    <span class="column-title">Price</span>
                                </div>
                            </th>
                            <th data-hide="phone">
                                <div class="table-header">
                                    <span class="column-title"># of Features</span>
                                </div>
                            </th>
                            <th data-class="expand">
                                <div class="table-header">
                                    <span class="column-title">Plan Length In Days</span>
                                </div>
                            </th>
                            <th data-class="expand">
                                <div class="table-header">
                                    <span class="column-title">Active</span>
                                </div>
                            </th>
                            <th width="30px">
                                <div class="table-header">
                                    <span class="column-title">Actions</span>
                                </div>
                            </th>
                        </tr>
                    </thead>
                </table>

            </div>
            <!-- /.card-body -->
        </div>
    </div>
</div>

<!-- #region scripts -->
@section Scripts
    {
    <script src="~/Scripts/Plan/PlanViewModel.js"></script>
    <script>
        PlanViewModel.planListView();
    </script>
}
<!-- #endregion -->

FMS/Views/Plan/ViewPlanFeature.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSAAS.cshtml";
}

<div id="content">
    <div class="panel panel-default">
        <div class=" panel-heading">
            <div class="row">
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-7">
                    <h3 class="box-title">Features</h3>
                </div>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="panel-body">
            <table id="tblPlanFeatures" class="table table-responsive dataTable table-striped">
                <thead>
                    <tr>
                        <th data-class="expand">
                            <div class="table-header">
                                <span class="column-title">Feature</span>
                            </div>
                        </th>
                        <th data-hide="phone">
                            <div class="table-header">
                                <span class="column-title">Price</span>
                            </div>
                        </th>
                    </tr>
                </thead>
            </table>
        </div>
        <!-- /.box-body -->
    </div>

</div>
<!-- #region scripts -->
@section Scripts
    {
    <script src="~/Scripts/Plan/PlanViewModel.js" asp-append-version="true"></script>
    <script>
        PlanViewModel.planFeatureListView();
    </script>
}
<!-- #endregion -->

FMS/Views/Plan/_AddEditPlanFeature.cshtml
@model FMS.Core.Models.PlanModel

@{
    string title = (Model != null && Model.Id == 0) ? "Add New Pricing Plan" : (Model != null && Model.IsReadMode) ? "View " + Model.Name : "Edit Pricing Plan";
    string buttonText = (Model != null && Model.IsReadMode) ? "View Features" : "Add Features";
    string featureModuleTitle = (Model != null && Model.Id == 0) ? "Add New Pricing Plan → Add Features" : (Model != null && Model.IsReadMode) ? "View " + Model.Name + " →  Features" : "Edit Pricing Plan → Edit Features";
}

<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title marketing-header">@title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <form role="form" method="post"
              id="frmAddNewPlanFeature"
              class="boxShadow"
              data-clear-form="false"
              data-post-type='ajax'
              action="/plan/updateplanmodal"
              data-success-method="PlanViewModel.updatePlanFeatureModalSuccess">
            @Html.HiddenFor(x => x.Id, new { @id = "plan-id" })
            @Html.EditorFor(x => x.Id, new { htmlAttributes = new { @class = "d-none" } })
            @Html.HiddenFor(x => x.CreatedBy, new { @id = "dbPlanFeatureCreatedBy" })
            <div class="card-body pl-5 pr-5">

                <div class="row" id="basicInfoModule">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                        <div class="form-group">
                            <label for="Name">Plan Name<span class="text-required"> *</span></label>
                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control", @id = "PlanName", placeholder = "Enter Plan Name" })
                            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label for="Price">Price <span class="text-required"> *</span></label>
                            <div class="input-icon">
                                @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Price, "", new { @class = "text-danger" })
                                <i>$</i>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Plan length">Plan length</label>
                            <div class="input-icon">
                                @Html.TextBoxFor(x => x.PlanLengthInDays, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.PlanLengthInDays, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Description">Plan Description</label>
                            @Html.TextAreaFor(x => x.Description, new { @class = "form-control", @rows = "5" })
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 @Model.planFeature" id="planFeature-feature">

                        <div class="row mt-3">
                            <div class="col-md-12">
                                <div class="input-group input-group-sm ">
                                    @Html.TextBoxFor(x => x.Feature, new { @class = "form-control", @id = "plan-feature", placeholder = "Enter Feature" })
                                    @Html.ValidationMessageFor(m => m.Feature, "", new { @class = "text-danger" })
                                    <span class="input-group-append">
                                        <button type="button" id="btn-formFeature" data-formId="frmAddNewFeature" onclick="PlanViewModel.addFeature(this)" class="btn btn-primary btn-flat ml-3">
                                            @if (Model.IsReadMode)
                                            {
                                                <i class="fa fa-eye mr-1"></i>
                                            }
                                            else
                                            {
                                                <i class="fa fa-plus mr-1"></i>
                                            }
                                            @buttonText
                                        </button>
                                    </span>
                                </div>
                                <button type="submit" id="btnfrmAddNewFeatureSubmit" class="d-none"></button>
                                <hr />
                                <div class="border m-3 border-dark text-center">
                                    <table class="dataTables_wrapper dt-bootstrap4 no-footer" id="tblPlanFeature">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="submit" id="btn-frmAddNewPlanFeature-submit" class="d-none btn btn-primary">Save</button>
                <div id="basicInfoModule-footer">
                    <button type="button" id="btnSavePlan" class="hideOnView ladda-button btn btn-primary" data-style="expand-left" data-formId="frmAddNewPlanFeature" onclick="PlanViewModel.savePlan(this)">Save</button>
                    <button type="button" class=" btn btn-outline-primary" data-dismiss="modal">Close</button>
                </div>
                <div class="d-none" id="planFeatureModule-footer">
                    <button type="button" id="btnShowPlanModule" class="btn btn-default notDisabled" onclick="PlanViewModel.showCurrentPanel(this)" data-viewName="basicInfoModule" data-title="@title">Back</button>
                    <button type="button" id="btnSavePlanFeature" class=" ladda-button btn btn-info" data-style="expand-left" onclick="PlanViewModel.updatePlanFeature(this)" data-backPageBtnId="btnShowPlanModule">Submit</button>
                </div>
            </div>
        </form>

    </div>
</div>

<!-- #region scripts -->
<script src="~/Scripts/Plan/PlanViewModel.js"></script>
<script>
    PlanViewModel.PlanFeatureListView($("#plan-id").val())
</script>
<script>
       preventFormSubmitOnEnterPress();
       $(document).ready(function() {
        var isReadMode =@Html.Raw(Json.Encode(Model.IsReadMode));
        if (isReadMode) {
            disabledFormInputs("frmAddNewPlanFeature");
        }
           if ($("#planModuleFeatureCheckBoxList input[type='checkbox']:checked").length > 0) {
               $("#planModuleFeatureCheckBoxList").removeClass("d-none");
        }
    });
</script>
<!-- #endregion -->